## 1. 고양이와 개는 몇 마리 있을까

SELECT ANIMAL_TYPE, COUNT(*) as count
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC

## 2. 동명 동물 수 찾기

SELECT NAME, COUNT(*) as COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(*)>1
ORDER BY NAME ASC

## 3. 입양 시각 구하기(1)

SELECT HOUR(datetime) as HOUR, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE HOUR BETWEEN '9' AND '20'
GROUP BY HOUR
ORDER BY HOUR ASC

