## 1. 없어진 기록 찾기

SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_OUTS as outs LEFT JOIN ANIMAL_INS as ins ON outs.ANIMAL_ID = ins.ANIMAL_ID
WHERE ins.ANIMAL_ID IS NULL


## 2. 있었는데요 없었습니다

SELECT outs.ANIMAL_ID, outs.NAME
FROM ANIMAL_OUTS as outs JOIN ANIMAL_INS as ins ON outs.ANIMAL_ID = ins.ANIMAL_ID
WHERE outs.DATETIME < ins.DATETIME
ORDER BY ins.DATETIME


## 3. 오랜 기간 보호한 동물(1)

SELECT ins.NAME , ins.DATETIME
FROM ANIMAL_INS as ins LEFT JOIN ANIMAL_OUTS as outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE outs.DATETIME IS NULL
ORDER BY ins.DATETIME ASC
LIMIT 0,3

## 4. 보호소에서 중성화한 동물

SELECT ins.ANIMAL_ID, ins.ANIMAL_TYPE, ins.NAME
FROM ANIMAL_INS as ins JOIN ANIMAL_OUTS as outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%' AND SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY ins.ANIMAL_ID
