1. 루시와 엘라 찾기

SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Sabrina', 'Mitty')
ORDER BY ANIMAL_ID ANS

2. 이름에 el이 들어가는 동물 찾기

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE '%el%' AND ANIMAL_TYPE = 'Dog'
ORDER BY NAME 

3. 중성화 여부 파악하기

## IF 사용 
SELECT ANIMAL_ID, NAME, IF(SEX_UPON_INTAKE LIKE 'Neutered%' OR SEX_UPON_INTAKE LIKE 'Spayed%', 'O', 'X') as '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

## CASE WHEN 사용
SELECT ANIMAL_ID, NAME, 
    CASE WHEN SEX_UPON_INTAKE LIKE 'Neutered%' OR SEX_UPON_INTAKE LIKE 'Spayed%'
    THEN 'O' ELSE 'X'
    END as '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID


4. 오랜 기간 보호한 동물(2)

SELECT ins.ANIMAL_ID, ins.NAME
FROM ANIMAL_INS as ins JOIN ANIMAL_OUTS as outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
ORDER BY (outs.DATETIME - ins.DATETIME) DESC
LIMIT 2

##DATEDIFF 도 가능
ORDER BY DATEDIFF(outs.DATETIME , ins.DATETIME) DESC  

5. DATETIME에서 DATE로 형 변환

SELECT ANIMAL_ID , NAME, date_format(DATETIME, '%Y-%m-%d') as '날짜'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID
